# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Accueil
      title: Accueil Hover
      path: homepage
      class: first
    - label: Tout les tutos
      path: tutos
      submenu:
          - label: Config
            path: categories_tutos/config
          - label: Back-end
            path: categories_tutos/back-end
          - label: Front-end
            path: categories_tutos/front-end
          - label: SEO
            path: categories_tutos/seo
    - label: Toutes les pages
      path: pages
      submenu:
          - label: Classiques
            path: categories_page/classiques
          - label: Avec template
            path: categories_page/avec-template
          - label: Sans template
            path: categories_page/sans-template


admin:
- label: Admin
  title: This is the first menu item.
  path: search
  class: admin
- label: Compte
  path: entry/1
- label: Deconnecter
  path: pages/
