# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Accueil
      title: Accueil Hover
      path: homepage
      class: first
    - label: Tout les tutos
      path: entry/1
      submenu:
          - label: Config
            path: categories/config
          - label: Back-end
            path: categories/back-end
          - label: Front-end
            path: categories/front-end
          - label: SEO
            path: categories/seo
    - label: All pages
      path: pages/
    - label: The Bolt site
      link: http://bolt.cm
      class: last

admin:
- label: Admin
  title: This is the first menu item.
  path: search
  class: admin
- label: Compte
  path: entry/1
- label: Deconnecter
  path: pages/
