# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Accueil
      title: Accueil Hover
      path: homepage
      class: first

    - label: Tout les tutos
      path: articles
      submenu:
          - label: Config
            path: categoriesarticles/config
          - label: Back-end
            path: categoriesarticles/back-end
          - label: Front-end
            path: categoriesarticles/front-end
          - label: SEO
            path: categoriesarticles/seo

    - label: Toutes les pages
      path: pages
      submenu:
          - label: Classiques
            path: categoriespages/generique
          - label: Avec template
            path: categoriespages/avec-template
          - label: Sans template
            path: categoriespages/sans-template


admin:
- label: Admin
  title: This is the first menu item.
  path: search
  class: admin
- label: Compte
  path: entry/1
- label: Deconnecter
  path: pages/
