# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Toto
      path: entry/1
      submenu:
          - label: Sub tt
            path: entry/2
          - label: Sub 2
            class: menu-item-class
            path: entry/3
          - label: Sub 3
            path: entry/4
          - label: Sub 4
            class: sub-class
            path: page/3
    - label: All pages
      path: pages/
    - label: The Bolt site
      link: http://bolt.cm
      class: last

admin:
- label: Admin
  title: This is the first menu item.
  path: search
  class: admin
- label: Compte
  path: entry/1
- label: Deconnecter
  path: pages/
