# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories_tutos:
    name: Categorie
    slug: categories_tutos
    singular_slug: categories_tuto
    behaves_like: categories
    multiple: true
    options: [ SEO, Back-end, Front-end, Config ]
#
categories_page:
    name: Categorie
    slug: categories_page
    singular_slug: categories_page
    behaves_like: categories
    multiple: true
    options: [ Classique, Sans-template, Avec-template ]
