# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]


typearticles:
    name: Type article
    slug: typearticles
    #le slug est généré automatiquement à partir du name si on ne le défini pas
    singular_slug: typearticle
    behaves_like: categories
    multiple: true
    options: { seo: "SEO", back-end: "Back-end", front-end: "Front-end", config: "Config" }
#
typepages:
    name: Type page
    slug: typepages
    singular_slug: typepage
    behaves_like: categories
    multiple: true
    options:  { generique: "Générique", avec-template: "Avec template", sans-template: "Sans template" }
